### ISSUE TITLE
As a player, I would like to see an escape menu such that it shows options for displaying other related windows so that I can change settings, save/load levels, exit the game

### ISSUE THREAD

**Issue by cagdasgerede** [cagdasgerede/tetris-1#24]
The game should have an escape menu which provides a window with options displaying such as:

- settings
- scoreboard
- exit

Implement template windows for each of these actions.

**Comment by aydinmercan** [comment]
Since this issue still has the label `not-claimed`, I'd like to be assigned to this task if it is still available.

- Aydin Mercan

**Comment by cagdasgerede** [comment]
@aydinmercan Bu issue kapalı. Başka bir issue öner lütfen.
